DB_NAME=morgendagens
DB_USERNAME=postgres
DB_PASSWORD=postgres
ISSUER=morgendagens
TOKEN_EXPIRE_TIME=3600000
SECRET_KEY=morgendagens-very-secret-key-256bit!!
RESEND_API_KEY=re_CX5JdfrW_8JabNH89HAFAmwFaPReiPNKe
EMAIL_FROM=emil@morgendagensmaaltid.dk