@baseUrl = {{url}}/api/message

### GET all messages
GET {{baseUrl}}/all
Accept: application/json
Authorization: Bearer {{authToken}}

### GET message by ID
GET {{baseUrl}}/1
Accept: application/json
Authorization: Bearer {{authToken}}

### POST create message
POST {{baseUrl}}/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "userId": 3,
  "thread": 1,
  "context": "HTTP test message",
  "date": "2025-03-05T10:00:00"
}

### PUT update message
PUT {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "userId": 3,
  "thread": 2,
  "context": "Updated HTTP test message",
  "date": "2025-03-05T11:15:00"
}

### DELETE message
DELETE {{baseUrl}}/23
Authorization: Bearer {{authToken}}
