@baseUrl = {{url}}/product-in-requests

### GET all product-in-requests
GET {{baseUrl}}/all
Accept: application/json

### GET product-in-request by ID
GET {{baseUrl}}/1
Accept: application/json
### POST create product-in-request
POST {{baseUrl}}/
Content-Type: application/json

{
  "requestId": 1,
  "productId": 1,
  "time": "10:30:00"
}

### PUT update product-in-request
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "requestId": 1,
  "productId": 2,
  "time": "15:45:00"
}

### DELETE product-in-request
DELETE {{baseUrl}}/1
