@baseUrl = {{url}}/api/request

### GET all requests
GET {{baseUrl}}/all
Accept: application/json
Authorization: Bearer {{authToken}}

### GET request by ID
GET {{baseUrl}}/1
Accept: application/json
Authorization: Bearer {{authToken}}

### POST create request
POST {{baseUrl}}/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "tenantId": 1,
  "startDate": "2026-03-13T08:00:00",
  "endDate": "2026-03-13T09:00:00",
  "location": "Copenhagen",
  "status": 1,
  "type": 1,
  "productInRequestIds": [1]
}

### PUT update request
PUT {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "tenantId": 1,
  "startDate": "2026-03-13T10:00:00",
  "endDate": "2026-03-13T12:00:00",
  "location": "Aarhus",
  "status": 2,
  "type": 2,
  "productInRequestIds": [1, 2]
}

### DELETE request
DELETE {{baseUrl}}/1
Authorization: Bearer {{authToken}}
